# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated posts client for the X API.
#
# This module provides a client for interacting with the posts
# endpoints of the X API. All methods, parameters, and response handling are
# generated from the OpenAPI specification.
#
# Generated automatically - do not edit manually.

require 'json'
require 'net/http'
require 'uri'
require_relative 'models'

module Xdk
  # Client for posts operations
  class PostsClient
    # @param client [Xdk::Client] the main API client
    def initialize(client)
      @client = client
    end

    # Get Post analytics

    # Retrieves analytics data for specified Posts within a defined time range.

    # @param ids [Array] A comma separated list of Post IDs. Up to 100 are allowed in a single request. (required)

    # @param end_time [String] YYYY-MM-DDTHH:mm:ssZ. The UTC timestamp representing the end of the time range. (required)

    # @param start_time [String] YYYY-MM-DDTHH:mm:ssZ. The UTC timestamp representing the start of the time range. (required)

    # @param granularity [String] The granularity for the search counts results. (required)

    # @param analytics_fields [Array, nil] A comma separated list of Analytics fields to display.

    # @return [Hash] API response
    def get_analytics(ids:, end_time:, start_time:, granularity:, analytics_fields: nil)
      # Build the request path
      path = '/2/tweets/analytics'

      # Build query parameters
      params = {}

      params['ids'] = ids.is_a?(Array) ? ids.join(',') : ids unless ids.nil?

      params['end_time'] = end_time unless end_time.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['granularity'] = granularity unless granularity.nil?

      unless analytics_fields.nil?
        params['analytics.fields'] =
          analytics_fields.is_a?(Array) ? analytics_fields.join(',') : analytics_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Search all Posts

    # Retrieves Posts from the full archive matching a search query.

    # @param query [String] One query/rule/filter for matching Posts. Refer to https://t.co/rulelength to identify the max query length. (required)

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The oldest UTC timestamp from which the Posts will be provided. Timestamp is in second granularity and is inclusive (i.e. 12:00:01 includes the first second of the minute).

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The newest, most recent UTC timestamp to which the Posts will be provided. Timestamp is in second granularity and is exclusive (i.e. 12:00:01 excludes the first second of the minute).

    # @param since_id [Object, nil] Returns results with a Post ID greater than (that is, more recent than) the specified ID.

    # @param until_id [Object, nil] Returns results with a Post ID less than (that is, older than) the specified ID.

    # @param max_results [Integer, nil] The maximum number of search results to be returned by a request.

    # @param next_token [Object, nil] This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.

    # @param sort_order [String, nil] This order in which to return results.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def search_all(query:, start_time: nil, end_time: nil, since_id: nil, until_id: nil, max_results: nil, next_token: nil,
                   pagination_token: nil, sort_order: nil, tweet_fields: nil, expansions: nil, media_fields: nil, poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/tweets/search/all'

      # Build query parameters
      params = {}

      params['query'] = query unless query.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      params['since_id'] = since_id unless since_id.nil?

      params['until_id'] = until_id unless until_id.nil?

      params['max_results'] = max_results unless max_results.nil?

      params['next_token'] = next_token unless next_token.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['sort_order'] = sort_order unless sort_order.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get Quoted Posts

    # Retrieves a list of Posts that quote a specific Post by its ID.

    # @param id [Object] A single Post ID. (required)

    # @param max_results [Integer, nil] The maximum number of results to be returned.

    # @param pagination_token [Object, nil] This parameter is used to get a specified 'page' of results.

    # @param exclude [Array, nil] The set of entities to exclude (e.g. 'replies' or 'retweets').

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def get_quoted(id:, max_results: nil, pagination_token: nil, exclude: nil, tweet_fields: nil, expansions: nil,
                   media_fields: nil, poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/tweets/{id}/quote_tweets'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['exclude'] = exclude.is_a?(Array) ? exclude.join(',') : exclude unless exclude.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get count of all Posts

    # Retrieves the count of Posts matching a search query from the full archive.

    # @param query [String] One query/rule/filter for matching Posts. Refer to https://t.co/rulelength to identify the max query length. (required)

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The oldest UTC timestamp from which the Posts will be provided. Timestamp is in second granularity and is inclusive (i.e. 12:00:01 includes the first second of the minute).

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The newest, most recent UTC timestamp to which the Posts will be provided. Timestamp is in second granularity and is exclusive (i.e. 12:00:01 excludes the first second of the minute).

    # @param since_id [Object, nil] Returns results with a Post ID greater than (that is, more recent than) the specified ID.

    # @param until_id [Object, nil] Returns results with a Post ID less than (that is, older than) the specified ID.

    # @param next_token [Object, nil] This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.

    # @param granularity [String, nil] The granularity for the search counts results.

    # @param search_count_fields [Array, nil] A comma separated list of SearchCount fields to display.

    # @return [Hash] API response
    def get_counts_all(query:, start_time: nil, end_time: nil, since_id: nil, until_id: nil, next_token: nil,
                       pagination_token: nil, granularity: nil, search_count_fields: nil)
      # Build the request path
      path = '/2/tweets/counts/all'

      # Build query parameters
      params = {}

      params['query'] = query unless query.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      params['since_id'] = since_id unless since_id.nil?

      params['until_id'] = until_id unless until_id.nil?

      params['next_token'] = next_token unless next_token.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['granularity'] = granularity unless granularity.nil?

      unless search_count_fields.nil?
        params['search_count.fields'] =
          search_count_fields.is_a?(Array) ? search_count_fields.join(',') : search_count_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get count of recent Posts

    # Retrieves the count of Posts from the last 7 days matching a search query.

    # @param query [String] One query/rule/filter for matching Posts. Refer to https://t.co/rulelength to identify the max query length. (required)

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The oldest UTC timestamp (from most recent 7 days) from which the Posts will be provided. Timestamp is in second granularity and is inclusive (i.e. 12:00:01 includes the first second of the minute).

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The newest, most recent UTC timestamp to which the Posts will be provided. Timestamp is in second granularity and is exclusive (i.e. 12:00:01 excludes the first second of the minute).

    # @param since_id [Object, nil] Returns results with a Post ID greater than (that is, more recent than) the specified ID.

    # @param until_id [Object, nil] Returns results with a Post ID less than (that is, older than) the specified ID.

    # @param next_token [Object, nil] This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.

    # @param granularity [String, nil] The granularity for the search counts results.

    # @param search_count_fields [Array, nil] A comma separated list of SearchCount fields to display.

    # @return [Hash] API response
    def get_counts_recent(query:, start_time: nil, end_time: nil, since_id: nil, until_id: nil, next_token: nil,
                          pagination_token: nil, granularity: nil, search_count_fields: nil)
      # Build the request path
      path = '/2/tweets/counts/recent'

      # Build query parameters
      params = {}

      params['query'] = query unless query.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      params['since_id'] = since_id unless since_id.nil?

      params['until_id'] = until_id unless until_id.nil?

      params['next_token'] = next_token unless next_token.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['granularity'] = granularity unless granularity.nil?

      unless search_count_fields.nil?
        params['search_count.fields'] =
          search_count_fields.is_a?(Array) ? search_count_fields.join(',') : search_count_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get Reposted by

    # Retrieves a list of Users who reposted a specific Post by its ID.

    # @param id [Object] A single Post ID. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_reposted_by(id:, max_results: nil, pagination_token: nil, user_fields: nil, expansions: nil,
                        tweet_fields: nil)
      # Build the request path
      path = '/2/tweets/{id}/retweeted_by'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Search recent Posts

    # Retrieves Posts from the last 7 days matching a search query.

    # @param query [String] One query/rule/filter for matching Posts. Refer to https://t.co/rulelength to identify the max query length. (required)

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The oldest UTC timestamp from which the Posts will be provided. Timestamp is in second granularity and is inclusive (i.e. 12:00:01 includes the first second of the minute).

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The newest, most recent UTC timestamp to which the Posts will be provided. Timestamp is in second granularity and is exclusive (i.e. 12:00:01 excludes the first second of the minute).

    # @param since_id [Object, nil] Returns results with a Post ID greater than (that is, more recent than) the specified ID.

    # @param until_id [Object, nil] Returns results with a Post ID less than (that is, older than) the specified ID.

    # @param max_results [Integer, nil] The maximum number of search results to be returned by a request.

    # @param next_token [Object, nil] This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.

    # @param sort_order [String, nil] This order in which to return results.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def search_recent(query:, start_time: nil, end_time: nil, since_id: nil, until_id: nil, max_results: nil, next_token: nil,
                      pagination_token: nil, sort_order: nil, tweet_fields: nil, expansions: nil, media_fields: nil, poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/tweets/search/recent'

      # Build query parameters
      params = {}

      params['query'] = query unless query.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      params['since_id'] = since_id unless since_id.nil?

      params['until_id'] = until_id unless until_id.nil?

      params['max_results'] = max_results unless max_results.nil?

      params['next_token'] = next_token unless next_token.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['sort_order'] = sort_order unless sort_order.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get Liking Users

    # Retrieves a list of Users who liked a specific Post by its ID.

    # @param id [Object] A single Post ID. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_liking_users(id:, max_results: nil, pagination_token: nil, user_fields: nil, expansions: nil,
                         tweet_fields: nil)
      # Build the request path
      path = '/2/tweets/{id}/liking_users'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get Posts by IDs

    # Retrieves details of multiple Posts by their IDs.

    # @param ids [Array] A comma separated list of Post IDs. Up to 100 are allowed in a single request. (required)

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def get_by_ids(ids:, tweet_fields: nil, expansions: nil, media_fields: nil, poll_fields: nil, user_fields: nil,
                   place_fields: nil)
      # Build the request path
      path = '/2/tweets'

      # Build query parameters
      params = {}

      params['ids'] = ids.is_a?(Array) ? ids.join(',') : ids unless ids.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Create or Edit Post

    # Creates a new Post for the authenticated user, or edits an existing Post when edit_options are provided.

    # @param body [Hash] Request body

    # @return [Hash] API response
    def create(body:)
      # Build the request path
      path = '/2/tweets'

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end

    # Get historical Post insights

    # Retrieves historical engagement metrics for specified Posts within a defined time range.

    # @param tweet_ids [Array] List of PostIds for historical metrics. (required)

    # @param end_time [String] YYYY-MM-DDTHH:mm:ssZ. The UTC timestamp representing the end of the time range. (required)

    # @param start_time [String] YYYY-MM-DDTHH:mm:ssZ. The UTC timestamp representing the start of the time range. (required)

    # @param granularity [String] granularity of metrics response. (required)

    # @param requested_metrics [Array] request metrics for historical request. (required)

    # @param engagement_fields [Array, nil] A comma separated list of Engagement fields to display.

    # @return [Hash] API response
    def get_insights_historical(tweet_ids:, end_time:, start_time:, granularity:, requested_metrics:,
                                engagement_fields: nil)
      # Build the request path
      path = '/2/insights/historical'

      # Build query parameters
      params = {}

      params['tweet_ids'] = tweet_ids.is_a?(Array) ? tweet_ids.join(',') : tweet_ids unless tweet_ids.nil?

      params['end_time'] = end_time unless end_time.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['granularity'] = granularity unless granularity.nil?

      unless requested_metrics.nil?
        params['requested_metrics'] =
          requested_metrics.is_a?(Array) ? requested_metrics.join(',') : requested_metrics
      end

      unless engagement_fields.nil?
        params['engagement.fields'] =
          engagement_fields.is_a?(Array) ? engagement_fields.join(',') : engagement_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get Post by ID

    # Retrieves details of a specific Post by its ID.

    # @param id [Object] A single Post ID. (required)

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def get_by_id(id:, tweet_fields: nil, expansions: nil, media_fields: nil, poll_fields: nil, user_fields: nil,
                  place_fields: nil)
      # Build the request path
      path = '/2/tweets/{id}'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Delete Post

    # Deletes a specific Post by its ID, if owned by the authenticated user.

    # @param id [Object] The ID of the Post to be deleted. (required)

    # @return [Hash] API response
    def delete(id:)
      # Build the request path
      path = '/2/tweets/{id}'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :delete, path: path, params: params)
    end

    # Get 28-hour Post insights

    # Retrieves engagement metrics for specified Posts over the last 28 hours.

    # @param tweet_ids [Array] List of PostIds for 28hr metrics. (required)

    # @param granularity [String] granularity of metrics response. (required)

    # @param requested_metrics [Array] request metrics for historical request. (required)

    # @param engagement_fields [Array, nil] A comma separated list of Engagement fields to display.

    # @return [Hash] API response
    def get_insights28hr(tweet_ids:, granularity:, requested_metrics:, engagement_fields: nil)
      # Build the request path
      path = '/2/insights/28hr'

      # Build query parameters
      params = {}

      params['tweet_ids'] = tweet_ids.is_a?(Array) ? tweet_ids.join(',') : tweet_ids unless tweet_ids.nil?

      params['granularity'] = granularity unless granularity.nil?

      unless requested_metrics.nil?
        params['requested_metrics'] =
          requested_metrics.is_a?(Array) ? requested_metrics.join(',') : requested_metrics
      end

      unless engagement_fields.nil?
        params['engagement.fields'] =
          engagement_fields.is_a?(Array) ? engagement_fields.join(',') : engagement_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Hide reply

    # Hides or unhides a reply to a conversation owned by the authenticated user.

    # @param tweet_id [Object] The ID of the reply that you want to hide or unhide. (required)

    # @param body [Hash] Request body

    # @return [Hash] API response
    def hide_reply(tweet_id:, body: nil)
      # Build the request path
      path = '/2/tweets/{tweet_id}/hidden'

      path = path.gsub('{tweet_id}', tweet_id.to_s)

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :put, path: path, params: params)
    end

    # Get Reposts

    # Retrieves a list of Posts that repost a specific Post by its ID.

    # @param id [Object] A single Post ID. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def get_reposts(id:, max_results: nil, pagination_token: nil, tweet_fields: nil, expansions: nil, media_fields: nil,
                    poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/tweets/{id}/retweets'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end
  end
end
