# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated posts models for the X API.
#
# This module provides lightweight model classes for request and response
# data structures for the posts endpoints. All models are
# generated from the OpenAPI specification and provide convenient attribute
# access over raw Hash data.
#
# Generated automatically - do not edit manually.

module Xdk
  module Posts
    # Response model for get_analytics
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetAnalyticsResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetAnalyticsResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetAnalyticsResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for search_all
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class SearchAllResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<SearchAllResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<SearchAllResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_quoted
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetQuotedResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetQuotedResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetQuotedResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_counts_all
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetCountsAllResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetCountsAllResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetCountsAllResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_counts_recent
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetCountsRecentResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetCountsRecentResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetCountsRecentResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_reposted_by
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetRepostedByResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetRepostedByResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetRepostedByResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for search_recent
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class SearchRecentResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<SearchRecentResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<SearchRecentResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_liking_users
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetLikingUsersResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetLikingUsersResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetLikingUsersResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_by_ids
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetByIdsResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetByIdsResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetByIdsResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for create
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class CreateRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<CreateRequest #{@data}>"
      end
    end

    # Response model for get_insights_historical
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetInsightsHistoricalResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetInsightsHistoricalResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetInsightsHistoricalResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_by_id
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetByIdResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetByIdResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetByIdResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for delete
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class DeleteResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<DeleteResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<DeleteResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_insights28hr
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetInsights28hrResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetInsights28hrResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetInsights28hrResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for hide_reply
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class HideReplyResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<HideReplyResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<HideReplyResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for hide_reply
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class HideReplyRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<HideReplyRequest #{@data}>"
      end
    end

    # Response model for get_reposts
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetRepostsResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetRepostsResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetRepostsResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end
  end
end
