# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated communities client for the X API.
#
# This module provides a client for interacting with the communities
# endpoints of the X API. All methods, parameters, and response handling are
# generated from the OpenAPI specification.
#
# Generated automatically - do not edit manually.

require 'json'
require 'net/http'
require 'uri'
require_relative 'models'

module Xdk
  # Client for communities operations
  class CommunitiesClient
    # @param client [Xdk::Client] the main API client
    def initialize(client)
      @client = client
    end

    # Get Community by ID

    # Retrieves details of a specific Community by its ID.

    # @param id [Object] The ID of the Community. (required)

    # @param community_fields [Array, nil] A comma separated list of Community fields to display.

    # @return [Hash] API response
    def get_by_id(id:, community_fields: nil)
      # Build the request path
      path = '/2/communities/{id}'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      unless community_fields.nil?
        params['community.fields'] =
          community_fields.is_a?(Array) ? community_fields.join(',') : community_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Search Communities

    # Retrieves a list of Communities matching the specified search query.

    # @param query [String] Query to search communities. (required)

    # @param max_results [Integer, nil] The maximum number of search results to be returned by a request.

    # @param next_token [Object, nil] This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.

    # @param community_fields [Array, nil] A comma separated list of Community fields to display.

    # @return [Hash] API response
    def search(query:, max_results: nil, next_token: nil, pagination_token: nil, community_fields: nil)
      # Build the request path
      path = '/2/communities/search'

      # Build query parameters
      params = {}

      params['query'] = query unless query.nil?

      params['max_results'] = max_results unless max_results.nil?

      params['next_token'] = next_token unless next_token.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      unless community_fields.nil?
        params['community.fields'] =
          community_fields.is_a?(Array) ? community_fields.join(',') : community_fields
      end

      @client.request(method: :get, path: path, params: params)
    end
  end
end
