# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated direct messages client for the X API.
#
# This module provides a client for interacting with the direct messages
# endpoints of the X API. All methods, parameters, and response handling are
# generated from the OpenAPI specification.
#
# Generated automatically - do not edit manually.

require 'json'
require 'net/http'
require 'uri'
require_relative 'models'

module Xdk
  # Client for direct messages operations
  class DirectMessagesClient
    # @param client [Xdk::Client] the main API client
    def initialize(client)
      @client = client
    end

    # Create DM message by conversation ID

    # Sends a new direct message to a specific conversation by its ID.

    # @param dm_conversation_id [String] The DM Conversation ID. (required)

    # @param body [Hash] Request body

    # @return [Hash] API response
    def create_by_conversation_id(dm_conversation_id:, body: nil)
      # Build the request path
      path = '/2/dm_conversations/{dm_conversation_id}/messages'

      path = path.gsub('{dm_conversation_id}', dm_conversation_id.to_s)

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end

    # Get DM events for a DM conversation

    # Retrieves direct message events for a specific conversation.

    # @param id [Object] The DM conversation ID. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get a specified 'page' of results.

    # @param event_types [Array, nil] The set of event_types to include in the results.

    # @param dm_event_fields [Array, nil] A comma separated list of DmEvent fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_events_by_conversation_id(id:, max_results: nil, pagination_token: nil, event_types: nil, dm_event_fields: nil,
                                      expansions: nil, media_fields: nil, user_fields: nil, tweet_fields: nil)
      # Build the request path
      path = '/2/dm_conversations/{id}/dm_events'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['event_types'] = event_types.is_a?(Array) ? event_types.join(',') : event_types unless event_types.nil?

      unless dm_event_fields.nil?
        params['dm_event.fields'] =
          dm_event_fields.is_a?(Array) ? dm_event_fields.join(',') : dm_event_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Create DM message by participant ID

    # Sends a new direct message to a specific participant by their ID.

    # @param participant_id [Object] The ID of the recipient user that will receive the DM. (required)

    # @param body [Hash] Request body

    # @return [Hash] API response
    def create_by_participant_id(participant_id:, body: nil)
      # Build the request path
      path = '/2/dm_conversations/with/{participant_id}/messages'

      path = path.gsub('{participant_id}', participant_id.to_s)

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end

    # Get DM events for a DM conversation

    # Retrieves direct message events for a specific conversation.

    # @param participant_id [Object] The ID of the participant user for the One to One DM conversation. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get a specified 'page' of results.

    # @param event_types [Array, nil] The set of event_types to include in the results.

    # @param dm_event_fields [Array, nil] A comma separated list of DmEvent fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_events_by_participant_id(participant_id:, max_results: nil, pagination_token: nil, event_types: nil,
                                     dm_event_fields: nil, expansions: nil, media_fields: nil, user_fields: nil, tweet_fields: nil)
      # Build the request path
      path = '/2/dm_conversations/with/{participant_id}/dm_events'

      path = path.gsub('{participant_id}', participant_id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['event_types'] = event_types.is_a?(Array) ? event_types.join(',') : event_types unless event_types.nil?

      unless dm_event_fields.nil?
        params['dm_event.fields'] =
          dm_event_fields.is_a?(Array) ? dm_event_fields.join(',') : dm_event_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get DM events

    # Retrieves a list of recent direct message events across all conversations.

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get a specified 'page' of results.

    # @param event_types [Array, nil] The set of event_types to include in the results.

    # @param dm_event_fields [Array, nil] A comma separated list of DmEvent fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_events(max_results: nil, pagination_token: nil, event_types: nil, dm_event_fields: nil, expansions: nil,
                   media_fields: nil, user_fields: nil, tweet_fields: nil)
      # Build the request path
      path = '/2/dm_events'

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['event_types'] = event_types.is_a?(Array) ? event_types.join(',') : event_types unless event_types.nil?

      unless dm_event_fields.nil?
        params['dm_event.fields'] =
          dm_event_fields.is_a?(Array) ? dm_event_fields.join(',') : dm_event_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Create DM conversation

    # Initiates a new direct message conversation with specified participants.

    # @param body [Hash] Request body

    # @return [Hash] API response
    def create_conversation(body: nil)
      # Build the request path
      path = '/2/dm_conversations'

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end

    # Get DM event by ID

    # Retrieves details of a specific direct message event by its ID.

    # @param event_id [Object] dm event id. (required)

    # @param dm_event_fields [Array, nil] A comma separated list of DmEvent fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_events_by_id(event_id:, dm_event_fields: nil, expansions: nil, media_fields: nil, user_fields: nil,
                         tweet_fields: nil)
      # Build the request path
      path = '/2/dm_events/{event_id}'

      path = path.gsub('{event_id}', event_id.to_s)

      # Build query parameters
      params = {}

      unless dm_event_fields.nil?
        params['dm_event.fields'] =
          dm_event_fields.is_a?(Array) ? dm_event_fields.join(',') : dm_event_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Delete DM event

    # Deletes a specific direct message event by its ID, if owned by the authenticated user.

    # @param event_id [Object] The ID of the direct-message event to delete. (required)

    # @return [Hash] API response
    def delete_events(event_id:)
      # Build the request path
      path = '/2/dm_events/{event_id}'

      path = path.gsub('{event_id}', event_id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :delete, path: path, params: params)
    end
  end
end
