# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated general client for the X API.
#
# This module provides a client for interacting with the general
# endpoints of the X API. All methods, parameters, and response handling are
# generated from the OpenAPI specification.
#
# Generated automatically - do not edit manually.

require 'json'
require 'net/http'
require 'uri'
require_relative 'models'

module Xdk
  # Client for general operations
  class GeneralClient
    # @param client [Xdk::Client] the main API client
    def initialize(client)
      @client = client
    end

    # Get OpenAPI Spec.

    # Retrieves the full OpenAPI Specification in JSON format. (See https://github.com/OAI/OpenAPI-Specification/blob/master/README.md)

    # @return [Hash] API response
    def get_open_api_spec
      # Build the request path
      path = '/2/openapi.json'

      # Build query parameters
      params = {}

      @client.request(method: :get, path: path, params: params)
    end
  end
end
