# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated structure tests for communities.
#
# This module contains tests that validate the structure and API surface
# of the communities client. These tests ensure that all expected
# methods exist and are callable.
#
# Generated automatically - do not edit manually.

require 'spec_helper'

RSpec.describe 'communities SDK structure' do
  let(:client) { Xdk::Client.new(bearer_token: 'test-token') }

  describe Xdk::CommunitiesClient do
    it 'is accessible from the main client via #communities' do
      expect(client.communities).to be_a(Xdk::CommunitiesClient)
    end

    it 'returns the same instance on repeated access (memoized)' do
      expect(client.communities).to equal(client.communities)
    end

    it 'has at least one public API method' do
      public_methods = Xdk::CommunitiesClient.public_instance_methods(false) - [:initialize]
      expect(public_methods).not_to be_empty
    end

    describe 'method arity' do
    end
  end

  describe 'Module structure' do
    it 'defines Xdk::CommunitiesClient' do
      expect(defined?(Xdk::CommunitiesClient)).to eq('constant')
    end

    it 'defines the Communities models module' do
      expect(defined?(Xdk::Communities)).to eq('constant')
    end
  end
end
