# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated activity models for the X API.
#
# This module provides lightweight model classes for request and response
# data structures for the activity endpoints. All models are
# generated from the OpenAPI specification and provide convenient attribute
# access over raw Hash data.
#
# Generated automatically - do not edit manually.

module Xdk
  module Activity
    # Response model for stream
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class StreamResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<StreamResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<StreamResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for update_subscription
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class UpdateSubscriptionResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<UpdateSubscriptionResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<UpdateSubscriptionResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for update_subscription
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class UpdateSubscriptionRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<UpdateSubscriptionRequest #{@data}>"
      end
    end

    # Response model for delete_subscription
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class DeleteSubscriptionResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<DeleteSubscriptionResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<DeleteSubscriptionResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_subscriptions
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetSubscriptionsResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetSubscriptionsResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetSubscriptionsResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for create_subscription
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class CreateSubscriptionResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<CreateSubscriptionResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<CreateSubscriptionResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for create_subscription
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class CreateSubscriptionRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<CreateSubscriptionRequest #{@data}>"
      end
    end
  end
end
