# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated media models for the X API.
#
# This module provides lightweight model classes for request and response
# data structures for the media endpoints. All models are
# generated from the OpenAPI specification and provide convenient attribute
# access over raw Hash data.
#
# Generated automatically - do not edit manually.

module Xdk
  module Media
    # Response model for initialize_upload
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class InitializeUploadResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<InitializeUploadResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<InitializeUploadResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for initialize_upload
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class InitializeUploadRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<InitializeUploadRequest #{@data}>"
      end
    end

    # Response model for get_by_keys
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetByKeysResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetByKeysResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetByKeysResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for create_metadata
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class CreateMetadataResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<CreateMetadataResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<CreateMetadataResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for create_metadata
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class CreateMetadataRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<CreateMetadataRequest #{@data}>"
      end
    end

    # Response model for get_analytics
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetAnalyticsResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetAnalyticsResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetAnalyticsResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_by_key
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetByKeyResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetByKeyResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetByKeyResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for finalize_upload
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class FinalizeUploadResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<FinalizeUploadResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<FinalizeUploadResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_upload_status
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetUploadStatusResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetUploadStatusResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetUploadStatusResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for upload
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class UploadResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<UploadResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<UploadResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for upload
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class UploadRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<UploadRequest #{@data}>"
      end
    end

    # Response model for create_subtitles
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class CreateSubtitlesResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<CreateSubtitlesResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<CreateSubtitlesResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for create_subtitles
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class CreateSubtitlesRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<CreateSubtitlesRequest #{@data}>"
      end
    end

    # Response model for delete_subtitles
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class DeleteSubtitlesResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<DeleteSubtitlesResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<DeleteSubtitlesResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for delete_subtitles
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class DeleteSubtitlesRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<DeleteSubtitlesRequest #{@data}>"
      end
    end

    # Response model for append_upload
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class AppendUploadResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<AppendUploadResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<AppendUploadResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for append_upload
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class AppendUploadRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<AppendUploadRequest #{@data}>"
      end
    end
  end
end
