# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated account activity client for the X API.
#
# This module provides a client for interacting with the account activity
# endpoints of the X API. All methods, parameters, and response handling are
# generated from the OpenAPI specification.
#
# Generated automatically - do not edit manually.

require 'json'
require 'net/http'
require 'uri'
require_relative 'models'

module Xdk
  # Client for account activity operations
  class AccountActivityClient
    # @param client [Xdk::Client] the main API client
    def initialize(client)
      @client = client
    end

    # Delete subscription

    # Deletes an Account Activity subscription for the given webhook and user ID.

    # @param webhook_id [Object] The webhook ID to check subscription against. (required)

    # @param user_id [Object] User ID to unsubscribe from. (required)

    # @return [Hash] API response
    def delete_subscription(webhook_id:, user_id:)
      # Build the request path
      path = '/2/account_activity/webhooks/{webhook_id}/subscriptions/{user_id}/all'

      path = path.gsub('{webhook_id}', webhook_id.to_s)

      path = path.gsub('{user_id}', user_id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :delete, path: path, params: params)
    end

    # Create replay job

    # Creates a replay job to retrieve activities from up to the past 5 days for all subscriptions associated with a given webhook.

    # @param webhook_id [Object] The unique identifier for the webhook configuration. (required)

    # @param from_date [String] The oldest (starting) UTC timestamp (inclusive) from which events will be provided, in `yyyymmddhhmm` format. (required)

    # @param to_date [String] The latest (ending) UTC timestamp (exclusive) up to which events will be provided, in `yyyymmddhhmm` format. (required)

    # @return [Hash] API response
    def create_replay_job(webhook_id:, from_date:, to_date:)
      # Build the request path
      path = '/2/account_activity/replay/webhooks/{webhook_id}/subscriptions/all'

      path = path.gsub('{webhook_id}', webhook_id.to_s)

      # Build query parameters
      params = {}

      params['from_date'] = from_date unless from_date.nil?

      params['to_date'] = to_date unless to_date.nil?

      @client.request(method: :post, path: path, params: params)
    end

    # Validate subscription

    # Checks a user’s Account Activity subscription for a given webhook.

    # @param webhook_id [Object] The webhook ID to check subscription against. (required)

    # @return [Hash] API response
    def validate_subscription(webhook_id:)
      # Build the request path
      path = '/2/account_activity/webhooks/{webhook_id}/subscriptions/all'

      path = path.gsub('{webhook_id}', webhook_id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :get, path: path, params: params)
    end

    # Create subscription

    # Creates an Account Activity subscription for the user and the given webhook.

    # @param webhook_id [Object] The webhook ID to check subscription against. (required)

    # @param body [Hash] Request body

    # @return [Hash] API response
    def create_subscription(webhook_id:, body: nil)
      # Build the request path
      path = '/2/account_activity/webhooks/{webhook_id}/subscriptions/all'

      path = path.gsub('{webhook_id}', webhook_id.to_s)

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end

    # Get subscriptions

    # Retrieves a list of all active subscriptions for a given webhook.

    # @param webhook_id [Object] The webhook ID to pull subscriptions for. (required)

    # @return [Hash] API response
    def get_subscriptions(webhook_id:)
      # Build the request path
      path = '/2/account_activity/webhooks/{webhook_id}/subscriptions/all/list'

      path = path.gsub('{webhook_id}', webhook_id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :get, path: path, params: params)
    end

    # Get subscription count

    # Retrieves a count of currently active Account Activity subscriptions.

    # @return [Hash] API response
    def get_subscription_count
      # Build the request path
      path = '/2/account_activity/subscriptions/count'

      # Build query parameters
      params = {}

      @client.request(method: :get, path: path, params: params)
    end
  end
end
