# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated users client for the X API.
#
# This module provides a client for interacting with the users
# endpoints of the X API. All methods, parameters, and response handling are
# generated from the OpenAPI specification.
#
# Generated automatically - do not edit manually.

require 'json'
require 'net/http'
require 'uri'
require_relative 'models'

module Xdk
  # Client for users operations
  class UsersClient
    # @param client [Xdk::Client] the main API client
    def initialize(client)
      @client = client
    end

    # Repost Post

    # Causes the authenticated user to repost a specific Post by its ID.

    # @param id [Object] The ID of the authenticated source User that is requesting to repost the Post. (required)

    # @param body [Hash] Request body

    # @return [Hash] API response
    def repost_post(id:, body: nil)
      # Build the request path
      path = '/2/users/{id}/retweets'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end

    # Get Bookmark folders

    # Retrieves a list of Bookmark folders created by the authenticated user.

    # @param id [Object] The ID of the authenticated source User for whom to return results. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results.

    # @return [Hash] API response
    def get_bookmark_folders(id:, max_results: nil, pagination_token: nil)
      # Build the request path
      path = '/2/users/{id}/bookmarks/folders'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      @client.request(method: :get, path: path, params: params)
    end

    # Unmute User

    # Causes the authenticated user to unmute a specific user by their ID.

    # @param source_user_id [Object] The ID of the authenticated source User that is requesting to unmute the target User. (required)

    # @param target_user_id [Object] The ID of the User that the source User is requesting to unmute. (required)

    # @return [Hash] API response
    def unmute_user(source_user_id:, target_user_id:)
      # Build the request path
      path = '/2/users/{source_user_id}/muting/{target_user_id}'

      path = path.gsub('{source_user_id}', source_user_id.to_s)

      path = path.gsub('{target_user_id}', target_user_id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :delete, path: path, params: params)
    end

    # Get Bookmarks by folder ID

    # Retrieves Posts in a specific Bookmark folder by its ID for the authenticated user.

    # @param id [Object] The ID of the authenticated source User for whom to return results. (required)

    # @param folder_id [Object] The ID of the Bookmark Folder that the authenticated User is trying to fetch Posts for. (required)

    # @return [Hash] API response
    def get_bookmarks_by_folder_id(id:, folder_id:)
      # Build the request path
      path = '/2/users/{id}/bookmarks/folders/{folder_id}'

      path = path.gsub('{id}', id.to_s)

      path = path.gsub('{folder_id}', folder_id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :get, path: path, params: params)
    end

    # Unfollow List

    # Causes the authenticated user to unfollow a specific List by its ID.

    # @param id [Object] The ID of the authenticated source User that will unfollow the List. (required)

    # @param list_id [Object] The ID of the List to unfollow. (required)

    # @return [Hash] API response
    def unfollow_list(id:, list_id:)
      # Build the request path
      path = '/2/users/{id}/followed_lists/{list_id}'

      path = path.gsub('{id}', id.to_s)

      path = path.gsub('{list_id}', list_id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :delete, path: path, params: params)
    end

    # Get followed Lists

    # Retrieves a list of Lists followed by a specific User by their ID.

    # @param id [Object] The ID of the User to lookup. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get a specified 'page' of results.

    # @param list_fields [Array, nil] A comma separated list of List fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @return [Hash] API response
    def get_followed_lists(id:, max_results: nil, pagination_token: nil, list_fields: nil, expansions: nil,
                           user_fields: nil)
      # Build the request path
      path = '/2/users/{id}/followed_lists'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['list.fields'] = list_fields.is_a?(Array) ? list_fields.join(',') : list_fields unless list_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      @client.request(method: :get, path: path, params: params)
    end

    # Follow List

    # Causes the authenticated user to follow a specific List by its ID.

    # @param id [Object] The ID of the authenticated source User that will follow the List. (required)

    # @param body [Hash] Request body

    # @return [Hash] API response
    def follow_list(id:, body: nil)
      # Build the request path
      path = '/2/users/{id}/followed_lists'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end

    # Get owned Lists

    # Retrieves a list of Lists owned by a specific User by their ID.

    # @param id [Object] The ID of the User to lookup. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get a specified 'page' of results.

    # @param list_fields [Array, nil] A comma separated list of List fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @return [Hash] API response
    def get_owned_lists(id:, max_results: nil, pagination_token: nil, list_fields: nil, expansions: nil,
                        user_fields: nil)
      # Build the request path
      path = '/2/users/{id}/owned_lists'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['list.fields'] = list_fields.is_a?(Array) ? list_fields.join(',') : list_fields unless list_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      @client.request(method: :get, path: path, params: params)
    end

    # Get User by ID

    # Retrieves details of a specific User by their ID.

    # @param id [Object] The ID of the User to lookup. (required)

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_by_id(id:, user_fields: nil, expansions: nil, tweet_fields: nil)
      # Build the request path
      path = '/2/users/{id}'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get muting

    # Retrieves a list of Users muted by the authenticated user.

    # @param id [Object] The ID of the authenticated source User for whom to return results. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_muting(id:, max_results: nil, pagination_token: nil, user_fields: nil, expansions: nil, tweet_fields: nil)
      # Build the request path
      path = '/2/users/{id}/muting'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Mute User

    # Causes the authenticated user to mute a specific User by their ID.

    # @param id [Object] The ID of the authenticated source User that is requesting to mute the target User. (required)

    # @param body [Hash] Request body

    # @return [Hash] API response
    def mute_user(id:, body: nil)
      # Build the request path
      path = '/2/users/{id}/muting'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end

    # Get Reposts of me

    # Retrieves a list of Posts that repost content from the authenticated user.

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def get_reposts_of_me(max_results: nil, pagination_token: nil, tweet_fields: nil, expansions: nil, media_fields: nil,
                          poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/users/reposts_of_me'

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Delete Bookmark

    # Removes a Post from the authenticated user’s Bookmarks by its ID.

    # @param id [Object] The ID of the authenticated source User whose bookmark is to be removed. (required)

    # @param tweet_id [Object] The ID of the Post that the source User is removing from bookmarks. (required)

    # @return [Hash] API response
    def delete_bookmark(id:, tweet_id:)
      # Build the request path
      path = '/2/users/{id}/bookmarks/{tweet_id}'

      path = path.gsub('{id}', id.to_s)

      path = path.gsub('{tweet_id}', tweet_id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :delete, path: path, params: params)
    end

    # Unfollow User

    # Causes the authenticated user to unfollow a specific user by their ID.

    # @param source_user_id [Object] The ID of the authenticated source User that is requesting to unfollow the target User. (required)

    # @param target_user_id [Object] The ID of the User that the source User is requesting to unfollow. (required)

    # @return [Hash] API response
    def unfollow_user(source_user_id:, target_user_id:)
      # Build the request path
      path = '/2/users/{source_user_id}/following/{target_user_id}'

      path = path.gsub('{source_user_id}', source_user_id.to_s)

      path = path.gsub('{target_user_id}', target_user_id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :delete, path: path, params: params)
    end

    # Get affiliates

    # Retrieves a list of Users who are affiliated with a specific organization User by their ID.

    # @param id [Object] The ID of the User to lookup. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get a specified 'page' of results.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_affiliates(id:, max_results: nil, pagination_token: nil, user_fields: nil, expansions: nil,
                       tweet_fields: nil)
      # Build the request path
      path = '/2/users/{id}/affiliates'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Block DMs

    # Blocks direct messages to or from a specific User by their ID for the authenticated user.

    # @param id [Object] The ID of the target User that the authenticated user requesting to block dms for. (required)

    # @return [Hash] API response
    def block_dms(id:)
      # Build the request path
      path = '/2/users/{id}/dm/block'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :post, path: path, params: params)
    end

    # Get blocking

    # Retrieves a list of Users blocked by the specified User ID.

    # @param id [Object] The ID of the authenticated source User for whom to return results. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get a specified 'page' of results.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_blocking(id:, max_results: nil, pagination_token: nil, user_fields: nil, expansions: nil, tweet_fields: nil)
      # Build the request path
      path = '/2/users/{id}/blocking'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get following

    # Retrieves a list of Users followed by a specific User by their ID.

    # @param id [Object] The ID of the User to lookup. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get a specified 'page' of results.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_following(id:, max_results: nil, pagination_token: nil, user_fields: nil, expansions: nil,
                      tweet_fields: nil)
      # Build the request path
      path = '/2/users/{id}/following'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Follow User

    # Causes the authenticated user to follow a specific user by their ID.

    # @param id [Object] The ID of the authenticated source User that is requesting to follow the target User. (required)

    # @param body [Hash] Request body

    # @return [Hash] API response
    def follow_user(id:, body: nil)
      # Build the request path
      path = '/2/users/{id}/following'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end

    # Get pinned Lists

    # Retrieves a list of Lists pinned by the authenticated user.

    # @param id [Object] The ID of the authenticated source User for whom to return results. (required)

    # @param list_fields [Array, nil] A comma separated list of List fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @return [Hash] API response
    def get_pinned_lists(id:, list_fields: nil, expansions: nil, user_fields: nil)
      # Build the request path
      path = '/2/users/{id}/pinned_lists'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['list.fields'] = list_fields.is_a?(Array) ? list_fields.join(',') : list_fields unless list_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      @client.request(method: :get, path: path, params: params)
    end

    # Pin List

    # Causes the authenticated user to pin a specific List by its ID.

    # @param id [Object] The ID of the authenticated source User that will pin the List. (required)

    # @param body [Hash] Request body

    # @return [Hash] API response
    def pin_list(id:, body:)
      # Build the request path
      path = '/2/users/{id}/pinned_lists'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end

    # Get Users by usernames

    # Retrieves details of multiple Users by their usernames.

    # @param usernames [Array] A list of usernames, comma-separated. (required)

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_by_usernames(usernames:, user_fields: nil, expansions: nil, tweet_fields: nil)
      # Build the request path
      path = '/2/users/by'

      # Build query parameters
      params = {}

      params['usernames'] = usernames.is_a?(Array) ? usernames.join(',') : usernames unless usernames.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get liked Posts

    # Retrieves a list of Posts liked by a specific User by their ID.

    # @param id [Object] The ID of the User to lookup. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def get_liked_posts(id:, max_results: nil, pagination_token: nil, tweet_fields: nil, expansions: nil, media_fields: nil,
                        poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/users/{id}/liked_tweets'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Search Users

    # Retrieves a list of Users matching a search query.

    # @param query [Object] TThe the query string by which to query for users. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param next_token [Object, nil] This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def search(query:, max_results: nil, next_token: nil, user_fields: nil, expansions: nil, tweet_fields: nil)
      # Build the request path
      path = '/2/users/search'

      # Build query parameters
      params = {}

      params['query'] = query unless query.nil?

      params['max_results'] = max_results unless max_results.nil?

      params['next_token'] = next_token unless next_token.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Like Post

    # Causes the authenticated user to Like a specific Post by its ID.

    # @param id [Object] The ID of the authenticated source User that is requesting to like the Post. (required)

    # @param body [Hash] Request body

    # @return [Hash] API response
    def like_post(id:, body: nil)
      # Build the request path
      path = '/2/users/{id}/likes'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end

    # Get Users by IDs

    # Retrieves details of multiple Users by their IDs.

    # @param ids [Array] A list of User IDs, comma-separated. You can specify up to 100 IDs. (required)

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_by_ids(ids:, user_fields: nil, expansions: nil, tweet_fields: nil)
      # Build the request path
      path = '/2/users'

      # Build query parameters
      params = {}

      params['ids'] = ids.is_a?(Array) ? ids.join(',') : ids unless ids.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get Bookmarks

    # Retrieves a list of Posts bookmarked by the authenticated user.

    # @param id [Object] The ID of the authenticated source User for whom to return results. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def get_bookmarks(id:, max_results: nil, pagination_token: nil, tweet_fields: nil, expansions: nil, media_fields: nil,
                      poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/users/{id}/bookmarks'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Create Bookmark

    # Adds a post to the authenticated user’s bookmarks.

    # @param id [Object] The ID of the authenticated source User for whom to add bookmarks. (required)

    # @param body [Hash] Request body

    # @return [Hash] API response
    def create_bookmark(id:, body:)
      # Build the request path
      path = '/2/users/{id}/bookmarks'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end

    # Get Timeline

    # Retrieves a reverse chronological list of Posts in the authenticated User’s Timeline.

    # @param id [Object] The ID of the authenticated source User to list Reverse Chronological Timeline Posts of. (required)

    # @param since_id [Object, nil] The minimum Post ID to be included in the result set. This parameter takes precedence over start_time if both are specified.

    # @param until_id [Object, nil] The maximum Post ID to be included in the result set. This parameter takes precedence over end_time if both are specified.

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results.

    # @param exclude [Array, nil] The set of entities to exclude (e.g. 'replies' or 'retweets').

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the Posts will be provided. The since_id parameter takes precedence if it is also specified.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Posts will be provided. The until_id parameter takes precedence if it is also specified.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def get_timeline(id:, since_id: nil, until_id: nil, max_results: nil, pagination_token: nil, exclude: nil,
                     start_time: nil, end_time: nil, tweet_fields: nil, expansions: nil, media_fields: nil, poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/users/{id}/timelines/reverse_chronological'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['since_id'] = since_id unless since_id.nil?

      params['until_id'] = until_id unless until_id.nil?

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['exclude'] = exclude.is_a?(Array) ? exclude.join(',') : exclude unless exclude.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Unpin List

    # Causes the authenticated user to unpin a specific List by its ID.

    # @param id [Object] The ID of the authenticated source User for whom to return results. (required)

    # @param list_id [Object] The ID of the List to unpin. (required)

    # @return [Hash] API response
    def unpin_list(id:, list_id:)
      # Build the request path
      path = '/2/users/{id}/pinned_lists/{list_id}'

      path = path.gsub('{id}', id.to_s)

      path = path.gsub('{list_id}', list_id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :delete, path: path, params: params)
    end

    # Get User by username

    # Retrieves details of a specific User by their username.

    # @param username [String] A username. (required)

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_by_username(username:, user_fields: nil, expansions: nil, tweet_fields: nil)
      # Build the request path
      path = '/2/users/by/username/{username}'

      path = path.gsub('{username}', username.to_s)

      # Build query parameters
      params = {}

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get followers

    # Retrieves a list of Users who follow a specific User by their ID.

    # @param id [Object] The ID of the User to lookup. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get a specified 'page' of results.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_followers(id:, max_results: nil, pagination_token: nil, user_fields: nil, expansions: nil,
                      tweet_fields: nil)
      # Build the request path
      path = '/2/users/{id}/followers'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Unlike Post

    # Causes the authenticated user to Unlike a specific Post by its ID.

    # @param id [Object] The ID of the authenticated source User that is requesting to unlike the Post. (required)

    # @param tweet_id [Object] The ID of the Post that the User is requesting to unlike. (required)

    # @return [Hash] API response
    def unlike_post(id:, tweet_id:)
      # Build the request path
      path = '/2/users/{id}/likes/{tweet_id}'

      path = path.gsub('{id}', id.to_s)

      path = path.gsub('{tweet_id}', tweet_id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :delete, path: path, params: params)
    end

    # Get List memberships

    # Retrieves a list of Lists that a specific User is a member of by their ID.

    # @param id [Object] The ID of the User to lookup. (required)

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get a specified 'page' of results.

    # @param list_fields [Array, nil] A comma separated list of List fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @return [Hash] API response
    def get_list_memberships(id:, max_results: nil, pagination_token: nil, list_fields: nil, expansions: nil,
                             user_fields: nil)
      # Build the request path
      path = '/2/users/{id}/list_memberships'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['list.fields'] = list_fields.is_a?(Array) ? list_fields.join(',') : list_fields unless list_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      @client.request(method: :get, path: path, params: params)
    end

    # Unblock DMs

    # Unblocks direct messages to or from a specific User by their ID for the authenticated user.

    # @param id [Object] The ID of the target User that the authenticated user requesting to unblock dms for. (required)

    # @return [Hash] API response
    def unblock_dms(id:)
      # Build the request path
      path = '/2/users/{id}/dm/unblock'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :post, path: path, params: params)
    end

    # Get mentions

    # Retrieves a list of Posts that mention a specific User by their ID.

    # @param id [Object] The ID of the User to lookup. (required)

    # @param since_id [Object, nil] The minimum Post ID to be included in the result set. This parameter takes precedence over start_time if both are specified.

    # @param until_id [Object, nil] The maximum Post ID to be included in the result set. This parameter takes precedence over end_time if both are specified.

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the Posts will be provided. The since_id parameter takes precedence if it is also specified.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Posts will be provided. The until_id parameter takes precedence if it is also specified.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def get_mentions(id:, since_id: nil, until_id: nil, max_results: nil, pagination_token: nil, start_time: nil,
                     end_time: nil, tweet_fields: nil, expansions: nil, media_fields: nil, poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/users/{id}/mentions'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['since_id'] = since_id unless since_id.nil?

      params['until_id'] = until_id unless until_id.nil?

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Unrepost Post

    # Causes the authenticated user to unrepost a specific Post by its ID.

    # @param id [Object] The ID of the authenticated source User that is requesting to repost the Post. (required)

    # @param source_tweet_id [Object] The ID of the Post that the User is requesting to unretweet. (required)

    # @return [Hash] API response
    def unrepost_post(id:, source_tweet_id:)
      # Build the request path
      path = '/2/users/{id}/retweets/{source_tweet_id}'

      path = path.gsub('{id}', id.to_s)

      path = path.gsub('{source_tweet_id}', source_tweet_id.to_s)

      # Build query parameters
      params = {}

      @client.request(method: :delete, path: path, params: params)
    end

    # Get Posts

    # Retrieves a list of posts authored by a specific User by their ID.

    # @param id [Object] The ID of the User to lookup. (required)

    # @param since_id [Object, nil] The minimum Post ID to be included in the result set. This parameter takes precedence over start_time if both are specified.

    # @param until_id [Object, nil] The maximum Post ID to be included in the result set. This parameter takes precedence over end_time if both are specified.

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [Object, nil] This parameter is used to get the next 'page' of results.

    # @param exclude [Array, nil] The set of entities to exclude (e.g. 'replies' or 'retweets').

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the Posts will be provided. The since_id parameter takes precedence if it is also specified.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Posts will be provided. The until_id parameter takes precedence if it is also specified.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def get_posts(id:, since_id: nil, until_id: nil, max_results: nil, pagination_token: nil, exclude: nil, start_time: nil,
                  end_time: nil, tweet_fields: nil, expansions: nil, media_fields: nil, poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/users/{id}/tweets'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      params['since_id'] = since_id unless since_id.nil?

      params['until_id'] = until_id unless until_id.nil?

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      params['exclude'] = exclude.is_a?(Array) ? exclude.join(',') : exclude unless exclude.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get my User

    # Retrieves details of the authenticated user.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def get_me(user_fields: nil, expansions: nil, tweet_fields: nil)
      # Build the request path
      path = '/2/users/me'

      # Build query parameters
      params = {}

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end
  end
end
