# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated structure tests for usage.
#
# This module contains tests that validate the structure and API surface
# of the usage client. These tests ensure that all expected
# methods exist and are callable.
#
# Generated automatically - do not edit manually.

require 'spec_helper'

RSpec.describe 'usage SDK structure' do
  let(:client) { Xdk::Client.new(bearer_token: 'test-token') }

  describe Xdk::UsageClient do
    it 'is accessible from the main client via #usage' do
      expect(client.usage).to be_a(Xdk::UsageClient)
    end

    it 'returns the same instance on repeated access (memoized)' do
      expect(client.usage).to equal(client.usage)
    end

    it 'has at least one public API method' do
      public_methods = Xdk::UsageClient.public_instance_methods(false) - [:initialize]
      expect(public_methods).not_to be_empty
    end

    describe 'method arity' do
    end
  end

  describe 'Module structure' do
    it 'defines Xdk::UsageClient' do
      expect(defined?(Xdk::UsageClient)).to eq('constant')
    end

    it 'defines the Usage models module' do
      expect(defined?(Xdk::Usage)).to eq('constant')
    end
  end
end
