# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated news models for the X API.
#
# This module provides lightweight model classes for request and response
# data structures for the news endpoints. All models are
# generated from the OpenAPI specification and provide convenient attribute
# access over raw Hash data.
#
# Generated automatically - do not edit manually.

module Xdk
  module News
    # Response model for search
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class SearchResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<SearchResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<SearchResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end
  end
end
