# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated compliance client for the X API.
#
# This module provides a client for interacting with the compliance
# endpoints of the X API. All methods, parameters, and response handling are
# generated from the OpenAPI specification.
#
# Generated automatically - do not edit manually.

require 'json'
require 'net/http'
require 'uri'
require_relative 'models'

module Xdk
  # Client for compliance operations
  class ComplianceClient
    # @param client [Xdk::Client] the main API client
    def initialize(client)
      @client = client
    end

    # Get Compliance Job by ID

    # Retrieves details of a specific Compliance Job by its ID.

    # @param id [Object] The ID of the Compliance Job to retrieve. (required)

    # @param compliance_job_fields [Array, nil] A comma separated list of ComplianceJob fields to display.

    # @return [Hash] API response
    def get_jobs_by_id(id:, compliance_job_fields: nil)
      # Build the request path
      path = '/2/compliance/jobs/{id}'

      path = path.gsub('{id}', id.to_s)

      # Build query parameters
      params = {}

      unless compliance_job_fields.nil?
        params['compliance_job.fields'] =
          compliance_job_fields.is_a?(Array) ? compliance_job_fields.join(',') : compliance_job_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get Compliance Jobs

    # Retrieves a list of Compliance Jobs filtered by job type and optional status.

    # @param type [String] Type of Compliance Job to list. (required)

    # @param status [String, nil] Status of Compliance Job to list.

    # @param compliance_job_fields [Array, nil] A comma separated list of ComplianceJob fields to display.

    # @return [Hash] API response
    def get_jobs(type:, status: nil, compliance_job_fields: nil)
      # Build the request path
      path = '/2/compliance/jobs'

      # Build query parameters
      params = {}

      params['type'] = type unless type.nil?

      params['status'] = status unless status.nil?

      unless compliance_job_fields.nil?
        params['compliance_job.fields'] =
          compliance_job_fields.is_a?(Array) ? compliance_job_fields.join(',') : compliance_job_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Create Compliance Job

    # Creates a new Compliance Job for the specified job type.

    # @param body [Hash] Request body

    # @return [Hash] API response
    def create_jobs(body:)
      # Build the request path
      path = '/2/compliance/jobs'

      # Build query parameters
      params = {}

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end
  end
end
