# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated usage client for the X API.
#
# This module provides a client for interacting with the usage
# endpoints of the X API. All methods, parameters, and response handling are
# generated from the OpenAPI specification.
#
# Generated automatically - do not edit manually.

require 'json'
require 'net/http'
require 'uri'
require_relative 'models'

module Xdk
  # Client for usage operations
  class UsageClient
    # @param client [Xdk::Client] the main API client
    def initialize(client)
      @client = client
    end

    # Get usage

    # Retrieves usage statistics for Posts over a specified number of days.

    # @param days [Integer, nil] The number of days for which you need usage for.

    # @param usage_fields [Array, nil] A comma separated list of Usage fields to display.

    # @return [Hash] API response
    def get(days: nil, usage_fields: nil)
      # Build the request path
      path = '/2/usage/tweets'

      # Build query parameters
      params = {}

      params['days'] = days unless days.nil?

      unless usage_fields.nil?
        params['usage.fields'] =
          usage_fields.is_a?(Array) ? usage_fields.join(',') : usage_fields
      end

      @client.request(method: :get, path: path, params: params)
    end
  end
end
