# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated chat models for the X API.
#
# This module provides lightweight model classes for request and response
# data structures for the chat endpoints. All models are
# generated from the OpenAPI specification and provide convenient attribute
# access over raw Hash data.
#
# Generated automatically - do not edit manually.

module Xdk
  module Chat
    # Response model for get_conversations
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetConversationsResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetConversationsResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetConversationsResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for send_typing_indicator
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class SendTypingIndicatorResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<SendTypingIndicatorResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<SendTypingIndicatorResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for media_download
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class MediaDownloadResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<MediaDownloadResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<MediaDownloadResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_user_public_keys
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetUserPublicKeysResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetUserPublicKeysResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetUserPublicKeysResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for add_user_public_key
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class AddUserPublicKeyResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<AddUserPublicKeyResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<AddUserPublicKeyResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for add_user_public_key
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class AddUserPublicKeyRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<AddUserPublicKeyRequest #{@data}>"
      end
    end

    # Response model for media_upload_finalize
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class MediaUploadFinalizeResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<MediaUploadFinalizeResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<MediaUploadFinalizeResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for media_upload_finalize
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class MediaUploadFinalizeRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<MediaUploadFinalizeRequest #{@data}>"
      end
    end

    # Response model for media_upload_initialize
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class MediaUploadInitializeResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<MediaUploadInitializeResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<MediaUploadInitializeResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for media_upload_initialize
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class MediaUploadInitializeRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<MediaUploadInitializeRequest #{@data}>"
      end
    end

    # Response model for mark_conversation_read
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class MarkConversationReadResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<MarkConversationReadResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<MarkConversationReadResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for mark_conversation_read
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class MarkConversationReadRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<MarkConversationReadRequest #{@data}>"
      end
    end

    # Response model for media_upload_append
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class MediaUploadAppendResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<MediaUploadAppendResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<MediaUploadAppendResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for media_upload_append
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class MediaUploadAppendRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<MediaUploadAppendRequest #{@data}>"
      end
    end

    # Request model for send_message
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class SendMessageRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<SendMessageRequest #{@data}>"
      end
    end

    # Response model for get_conversation
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetConversationResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetConversationResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetConversationResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end
  end
end
