# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated structure tests for posts.
#
# This module contains tests that validate the structure and API surface
# of the posts client. These tests ensure that all expected
# methods exist and are callable.
#
# Generated automatically - do not edit manually.

require 'spec_helper'

RSpec.describe 'posts SDK structure' do
  let(:client) { Xdk::Client.new(bearer_token: 'test-token') }

  describe Xdk::PostsClient do
    it 'is accessible from the main client via #posts' do
      expect(client.posts).to be_a(Xdk::PostsClient)
    end

    it 'returns the same instance on repeated access (memoized)' do
      expect(client.posts).to equal(client.posts)
    end

    it 'has at least one public API method' do
      public_methods = Xdk::PostsClient.public_instance_methods(false) - [:initialize]
      expect(public_methods).not_to be_empty
    end

    describe 'method arity' do
    end
  end

  describe 'Module structure' do
    it 'defines Xdk::PostsClient' do
      expect(defined?(Xdk::PostsClient)).to eq('constant')
    end

    it 'defines the Posts models module' do
      expect(defined?(Xdk::Posts)).to eq('constant')
    end
  end
end
