[package]
name = "xdk-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
xdk-gen = { path = "../xdk-gen" }
xdk-openapi = { path = "../xdk-openapi" }
clap = { version = "4.5.1", features = ["derive"] }
anyhow = "1.0.79"
serde_json = { workspace = true }
