# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated stream client for the X API.
#
# This module provides a client for interacting with the stream
# endpoints of the X API. All methods, parameters, and response handling are
# generated from the OpenAPI specification.
#
# Generated automatically - do not edit manually.

require 'json'
require 'net/http'
require 'uri'
require_relative 'models'

module Xdk
  # Client for stream operations
  class StreamClient
    # @param client [Xdk::Client] the main API client
    def initialize(client)
      @client = client
    end

    # Stream Posts compliance data

    # Streams all compliance data related to Posts.

    # @param partition [Integer] The partition number. (required)

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the Post Compliance events will be provided.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Post Compliance events will be provided.

    # @return [Hash] API response
    def posts_compliance(partition:, backfill_minutes: nil, start_time: nil, end_time: nil)
      # Build the request path
      path = '/2/tweets/compliance/stream'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      params['partition'] = partition unless partition.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      @client.request(method: :get, path: path, params: params)
    end

    # Stream sampled Likes

    # Streams a 10% sample of public Likes in real-time.

    # @param partition [Integer] The partition number. (required)

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp to which the Likes will be provided.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Posts will be provided.

    # @param like_with_tweet_author_fields [Array, nil] A comma separated list of LikeWithTweetAuthor fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def likes_sample10(partition:, backfill_minutes: nil, start_time: nil, end_time: nil,
                       like_with_tweet_author_fields: nil, expansions: nil, user_fields: nil, tweet_fields: nil)
      # Build the request path
      path = '/2/likes/sample10/stream'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      params['partition'] = partition unless partition.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      unless like_with_tweet_author_fields.nil?
        params['like_with_tweet_author.fields'] =
          like_with_tweet_author_fields.is_a?(Array) ? like_with_tweet_author_fields.join(',') : like_with_tweet_author_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Stream all Likes

    # Streams all public Likes in real-time.

    # @param partition [Integer] The partition number. (required)

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp to which the Likes will be provided.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Posts will be provided.

    # @param like_with_tweet_author_fields [Array, nil] A comma separated list of LikeWithTweetAuthor fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @return [Hash] API response
    def likes_firehose(partition:, backfill_minutes: nil, start_time: nil, end_time: nil,
                       like_with_tweet_author_fields: nil, expansions: nil, user_fields: nil, tweet_fields: nil)
      # Build the request path
      path = '/2/likes/firehose/stream'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      params['partition'] = partition unless partition.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      unless like_with_tweet_author_fields.nil?
        params['like_with_tweet_author.fields'] =
          like_with_tweet_author_fields.is_a?(Array) ? like_with_tweet_author_fields.join(',') : like_with_tweet_author_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get stream rules

    # Retrieves the active rule set or a subset of rules for the filtered stream.

    # @param ids [Array, nil] A comma-separated list of Rule IDs.

    # @param max_results [Integer, nil] The maximum number of results.

    # @param pagination_token [String, nil] This value is populated by passing the 'next_token' returned in a request to paginate through results.

    # @return [Hash] API response
    def get_rules(ids: nil, max_results: nil, pagination_token: nil)
      # Build the request path
      path = '/2/tweets/search/stream/rules'

      # Build query parameters
      params = {}

      params['ids'] = ids.is_a?(Array) ? ids.join(',') : ids unless ids.nil?

      params['max_results'] = max_results unless max_results.nil?

      params['pagination_token'] = pagination_token unless pagination_token.nil?

      @client.request(method: :get, path: path, params: params)
    end

    # Update stream rules

    # Adds or deletes rules from the active rule set for the filtered stream.

    # @param dry_run [Boolean, nil] Dry Run can be used with both the add and delete action, with the expected result given, but without actually taking any action in the system (meaning the end state will always be as it was when the request was submitted). This is particularly useful to validate rule changes.

    # @param delete_all [Boolean, nil] Delete All can be used to delete all of the rules associated this client app, it should be specified with no other parameters. Once deleted, rules cannot be recovered.

    # @param body [Hash] Request body

    # @return [Hash] API response
    def update_rules(body:, dry_run: nil, delete_all: nil)
      # Build the request path
      path = '/2/tweets/search/stream/rules'

      # Build query parameters
      params = {}

      params['dry_run'] = dry_run unless dry_run.nil?

      params['delete_all'] = delete_all unless delete_all.nil?

      # Prepare request body
      if body.is_a?(Hash)
        body
      else
        (body.nil? ? nil : body)
      end

      @client.request(method: :post, path: path, params: params)
    end

    # Stream Japanese Posts

    # Streams all public Japanese-language Posts in real-time.

    # @param partition [Integer] The partition number. (required)

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp to which the Posts will be provided.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Posts will be provided.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def posts_firehose_ja(partition:, backfill_minutes: nil, start_time: nil, end_time: nil, tweet_fields: nil,
                          expansions: nil, media_fields: nil, poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/tweets/firehose/stream/lang/ja'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      params['partition'] = partition unless partition.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Stream all Posts

    # Streams all public Posts in real-time.

    # @param partition [Integer] The partition number. (required)

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp to which the Posts will be provided.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Posts will be provided.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def posts_firehose(partition:, backfill_minutes: nil, start_time: nil, end_time: nil, tweet_fields: nil, expansions: nil,
                       media_fields: nil, poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/tweets/firehose/stream'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      params['partition'] = partition unless partition.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Stream Post labels

    # Streams all labeling events applied to Posts.

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the Post labels will be provided.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp from which the Post labels will be provided.

    # @return [Hash] API response
    def labels_compliance(backfill_minutes: nil, start_time: nil, end_time: nil)
      # Build the request path
      path = '/2/tweets/label/stream'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      @client.request(method: :get, path: path, params: params)
    end

    # Stream Likes compliance data

    # Streams all compliance data related to Likes for Users.

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the Likes Compliance events will be provided.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp from which the Likes Compliance events will be provided.

    # @return [Hash] API response
    def likes_compliance(backfill_minutes: nil, start_time: nil, end_time: nil)
      # Build the request path
      path = '/2/likes/compliance/stream'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      @client.request(method: :get, path: path, params: params)
    end

    # Stream 10% sampled Posts

    # Streams a 10% sample of public Posts in real-time.

    # @param partition [Integer] The partition number. (required)

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp to which the Posts will be provided.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Posts will be provided.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def posts_sample10(partition:, backfill_minutes: nil, start_time: nil, end_time: nil, tweet_fields: nil, expansions: nil,
                       media_fields: nil, poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/tweets/sample10/stream'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      params['partition'] = partition unless partition.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Get stream rule counts

    # Retrieves the count of rules in the active rule set for the filtered stream.

    # @param rules_count_fields [Array, nil] A comma separated list of RulesCount fields to display.

    # @return [Hash] API response
    def get_rule_counts(rules_count_fields: nil)
      # Build the request path
      path = '/2/tweets/search/stream/rules/counts'

      # Build query parameters
      params = {}

      unless rules_count_fields.nil?
        params['rules_count.fields'] =
          rules_count_fields.is_a?(Array) ? rules_count_fields.join(',') : rules_count_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Stream Users compliance data

    # Streams all compliance data related to Users.

    # @param partition [Integer] The partition number. (required)

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the User Compliance events will be provided.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp from which the User Compliance events will be provided.

    # @return [Hash] API response
    def users_compliance(partition:, backfill_minutes: nil, start_time: nil, end_time: nil)
      # Build the request path
      path = '/2/users/compliance/stream'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      params['partition'] = partition unless partition.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      @client.request(method: :get, path: path, params: params)
    end

    # Stream sampled Posts

    # Streams a 1% sample of public Posts in real-time.

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def posts_sample(backfill_minutes: nil, tweet_fields: nil, expansions: nil, media_fields: nil, poll_fields: nil,
                     user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/tweets/sample/stream'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Stream filtered Posts

    # Streams Posts in real-time matching the active rule set.

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the Posts will be provided.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Posts will be provided.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def posts(backfill_minutes: nil, start_time: nil, end_time: nil, tweet_fields: nil, expansions: nil, media_fields: nil,
              poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/tweets/search/stream'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Stream Portuguese Posts

    # Streams all public Portuguese-language Posts in real-time.

    # @param partition [Integer] The partition number. (required)

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp to which the Posts will be provided.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Posts will be provided.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def posts_firehose_pt(partition:, backfill_minutes: nil, start_time: nil, end_time: nil, tweet_fields: nil,
                          expansions: nil, media_fields: nil, poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/tweets/firehose/stream/lang/pt'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      params['partition'] = partition unless partition.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Stream Korean Posts

    # Streams all public Korean-language Posts in real-time.

    # @param partition [Integer] The partition number. (required)

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp to which the Posts will be provided.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Posts will be provided.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def posts_firehose_ko(partition:, backfill_minutes: nil, start_time: nil, end_time: nil, tweet_fields: nil,
                          expansions: nil, media_fields: nil, poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/tweets/firehose/stream/lang/ko'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      params['partition'] = partition unless partition.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end

    # Stream English Posts

    # Streams all public English-language Posts in real-time.

    # @param partition [Integer] The partition number. (required)

    # @param backfill_minutes [Integer, nil] The number of minutes of backfill requested.

    # @param start_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp to which the Posts will be provided.

    # @param end_time [String, nil] YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Posts will be provided.

    # @param tweet_fields [Array, nil] A comma separated list of Tweet fields to display.

    # @param expansions [Array, nil] A comma separated list of fields to expand.

    # @param media_fields [Array, nil] A comma separated list of Media fields to display.

    # @param poll_fields [Array, nil] A comma separated list of Poll fields to display.

    # @param user_fields [Array, nil] A comma separated list of User fields to display.

    # @param place_fields [Array, nil] A comma separated list of Place fields to display.

    # @return [Hash] API response
    def posts_firehose_en(partition:, backfill_minutes: nil, start_time: nil, end_time: nil, tweet_fields: nil,
                          expansions: nil, media_fields: nil, poll_fields: nil, user_fields: nil, place_fields: nil)
      # Build the request path
      path = '/2/tweets/firehose/stream/lang/en'

      # Build query parameters
      params = {}

      params['backfill_minutes'] = backfill_minutes unless backfill_minutes.nil?

      params['partition'] = partition unless partition.nil?

      params['start_time'] = start_time unless start_time.nil?

      params['end_time'] = end_time unless end_time.nil?

      unless tweet_fields.nil?
        params['tweet.fields'] =
          tweet_fields.is_a?(Array) ? tweet_fields.join(',') : tweet_fields
      end

      params['expansions'] = expansions.is_a?(Array) ? expansions.join(',') : expansions unless expansions.nil?

      unless media_fields.nil?
        params['media.fields'] =
          media_fields.is_a?(Array) ? media_fields.join(',') : media_fields
      end

      params['poll.fields'] = poll_fields.is_a?(Array) ? poll_fields.join(',') : poll_fields unless poll_fields.nil?

      params['user.fields'] = user_fields.is_a?(Array) ? user_fields.join(',') : user_fields unless user_fields.nil?

      unless place_fields.nil?
        params['place.fields'] =
          place_fields.is_a?(Array) ? place_fields.join(',') : place_fields
      end

      @client.request(method: :get, path: path, params: params)
    end
  end
end
