# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated stream models for the X API.
#
# This module provides lightweight model classes for request and response
# data structures for the stream endpoints. All models are
# generated from the OpenAPI specification and provide convenient attribute
# access over raw Hash data.
#
# Generated automatically - do not edit manually.

module Xdk
  module Stream
    # Response model for posts_compliance
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class PostsComplianceResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<PostsComplianceResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<PostsComplianceResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for likes_sample10
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class LikesSample10Response
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<LikesSample10Response data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<LikesSample10Response data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for likes_firehose
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class LikesFirehoseResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<LikesFirehoseResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<LikesFirehoseResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_rules
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetRulesResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetRulesResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetRulesResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for update_rules
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class UpdateRulesResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<UpdateRulesResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<UpdateRulesResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Request model for update_rules
    #
    # Provides a structured way to build request bodies. Can be initialized
    # with a Hash or keyword arguments; serializes to a Hash for the HTTP layer.
    class UpdateRulesRequest
      # @return [Hash] the raw request data
      attr_reader :data

      # @param attrs [Hash] request body attributes
      def initialize(**attrs)
        @data = attrs.transform_keys(&:to_s)
      end

      # Convert to a Hash suitable for JSON serialization
      # @return [Hash]
      def to_h
        @data
      end

      # Convert to JSON string
      # @return [String]
      def to_json(*args)
        @data.to_json(*args)
      end

      # @return [String]
      def to_s
        "#<UpdateRulesRequest #{@data}>"
      end
    end

    # Response model for posts_firehose_ja
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class PostsFirehoseJaResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<PostsFirehoseJaResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<PostsFirehoseJaResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for posts_firehose
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class PostsFirehoseResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<PostsFirehoseResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<PostsFirehoseResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for labels_compliance
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class LabelsComplianceResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<LabelsComplianceResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<LabelsComplianceResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for likes_compliance
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class LikesComplianceResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<LikesComplianceResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<LikesComplianceResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for posts_sample10
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class PostsSample10Response
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<PostsSample10Response data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<PostsSample10Response data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for get_rule_counts
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class GetRuleCountsResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<GetRuleCountsResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<GetRuleCountsResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for users_compliance
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class UsersComplianceResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<UsersComplianceResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<UsersComplianceResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for posts_sample
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class PostsSampleResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<PostsSampleResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<PostsSampleResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for posts
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class PostsResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<PostsResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<PostsResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for posts_firehose_pt
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class PostsFirehosePtResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<PostsFirehosePtResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<PostsFirehosePtResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for posts_firehose_ko
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class PostsFirehoseKoResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<PostsFirehoseKoResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<PostsFirehoseKoResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end

    # Response model for posts_firehose_en
    #
    # Wraps the raw API response Hash and provides attribute-style access
    # to common top-level fields (data, meta, errors, includes).
    class PostsFirehoseEnResponse
      # @return [Object, nil] the primary response data
      attr_reader :data

      # @return [Hash, nil] pagination metadata (next_token, result_count, etc.)
      attr_reader :meta

      # @return [Array<Hash>, nil] error objects returned by the API
      attr_reader :errors

      # @return [Hash, nil] expansion includes (users, tweets, media, etc.)
      attr_reader :includes

      # @return [Hash] the complete raw API response
      attr_reader :raw

      # @param hash [Hash] the parsed JSON response from the API
      def initialize(hash)
        hash = {} unless hash.is_a?(Hash)
        @raw = hash
        @data = hash['data']
        @meta = hash['meta']
        @errors = hash['errors']
        @includes = hash['includes']
      end

      # Access any top-level key from the raw response
      # @param key [String] the key to look up
      # @return [Object, nil]
      def [](key)
        @raw[key]
      end

      # @return [String]
      def to_s
        "#<PostsFirehoseEnResponse data=#{@data.class}>"
      end

      # @return [String]
      def inspect
        "#<PostsFirehoseEnResponse data=#{@data.inspect} meta=#{@meta.inspect}>"
      end
    end
  end
end
