# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated structure tests for community notes.
#
# This module contains tests that validate the structure and API surface
# of the community notes client. These tests ensure that all expected
# methods exist and are callable.
#
# Generated automatically - do not edit manually.

require 'spec_helper'

RSpec.describe 'community notes SDK structure' do
  let(:client) { Xdk::Client.new(bearer_token: 'test-token') }

  describe Xdk::CommunityNotesClient do
    it 'is accessible from the main client via #community_notes' do
      expect(client.community_notes).to be_a(Xdk::CommunityNotesClient)
    end

    it 'returns the same instance on repeated access (memoized)' do
      expect(client.community_notes).to equal(client.community_notes)
    end

    it 'has at least one public API method' do
      public_methods = Xdk::CommunityNotesClient.public_instance_methods(false) - [:initialize]
      expect(public_methods).not_to be_empty
    end

    describe 'method arity' do
    end
  end

  describe 'Module structure' do
    it 'defines Xdk::CommunityNotesClient' do
      expect(defined?(Xdk::CommunityNotesClient)).to eq('constant')
    end

    it 'defines the CommunityNotes models module' do
      expect(defined?(Xdk::CommunityNotes)).to eq('constant')
    end
  end
end
