# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
# frozen_string_literal: true

# Auto-generated structure tests for general.
#
# This module contains tests that validate the structure and API surface
# of the general client. These tests ensure that all expected
# methods exist and are callable.
#
# Generated automatically - do not edit manually.

require 'spec_helper'

RSpec.describe 'general SDK structure' do
  let(:client) { Xdk::Client.new(bearer_token: 'test-token') }

  describe Xdk::GeneralClient do
    it 'is accessible from the main client via #general' do
      expect(client.general).to be_a(Xdk::GeneralClient)
    end

    it 'returns the same instance on repeated access (memoized)' do
      expect(client.general).to equal(client.general)
    end

    it 'has at least one public API method' do
      public_methods = Xdk::GeneralClient.public_instance_methods(false) - [:initialize]
      expect(public_methods).not_to be_empty
    end

    describe 'method arity' do
    end
  end

  describe 'Module structure' do
    it 'defines Xdk::GeneralClient' do
      expect(defined?(Xdk::GeneralClient)).to eq('constant')
    end

    it 'defines the General models module' do
      expect(defined?(Xdk::General)).to eq('constant')
    end
  end
end
